<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>14.0.0</Version>
    <Authors>UMB</Authors>
    <Company>UMB</Company>
    <AssemblyVersion>14.0.0</AssemblyVersion>
    <FileVersion>14.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.2" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="Telstock.Encrypter" Version="2.1.0" />
  </ItemGroup>

</Project>
