<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NLog" Version="6.1.2" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="10.0.5" />
    <PackageReference Include="System.Management" Version="10.0.5" />
    <PackageReference Include="Telstock.Encrypter" Version="2.1.0" />
  </ItemGroup>

</Project>
